# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-02 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvte',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
