# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-02 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_post_upvte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvte',
            new_name='downvote',
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
