# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-04 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0011_auto_20190904_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='basic_app.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='votes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='post',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('post', 'user')]),
        ),
    ]
