# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-05 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_auto_20190905_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
